name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code.
        uses: actions/checkout@v4

      - name: Build BE Docker image.
        run: docker build -t nutrition-specs-be:latest ./be

      - name: Run BE Docker images.
        run: docker run -d -p 8000:80 --name nutrition-specs-be nutrition-specs-be:latest

      - name: Wait for the BE service to be ready.
        run: |
          for i in {1..10}; do
            if nc -z localhost 8000; then
              echo "BE service is ready."
              break
            fi
              echo "Waiting for BE service to be ready."
              sleep 3
          done

      - name: Setup Node.js.
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies.
        working-directory: ./fe
        run: npm ci

      - name: Build FE app.
        working-directory: ./fe
        run: npm run build

      - name: Remove BE Docker container.
        run: |
          docker stop nutrition-specs-be
          docker rm nutrition-specs-be

      - name: Configure AWS credentials.
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload FE to AWS S3
        run: aws s3 sync ./fe/dist s3://${{ secrets.S3_BUCKET_NAME }} --delete

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Tag Docker image
        run: docker tag nutrition-specs-be:latest  ${{ secrets.ECR_REPOSITORY_URI }}:latest

      - name: Push to Amazon ECR
        run: docker push ${{ secrets.ECR_REPOSITORY_URI }}:latest


